// One Sheet tab per table. Column order here is the header row order.

export const SCHEMA = {
  Settings: ['key', 'value'],
  Users: [
    'id',
    'name',
    'email',
    'class',
    'role',
    'target_band',
    'exam_date',
    'timezone',
    'consent_at',
    'created_at',
  ],
  Classes: ['id', 'label', 'active'],
  LoginTokens: ['token_hash', 'user_id', 'expires_at', 'used_at'],
  Sessions: ['token_hash', 'user_id', 'expires_at', 'created_at'],
  Topics: ['id', 'label', 'active'],
  Essays: [
    'id',
    'student_id',
    'parent_essay_id',
    'mode',
    'assignment_id',
    'started_at',
    'time_used_seconds',
    'auto_submitted',
    'over_time',
    'paste_attempts',
    'task_type',
    'topic_id',
    'prompt',
    'body',
    'word_count',
    'image_file_id',
    'status',
    'drive_folder_id',
    'drive_sync_status',
    'saved_at',
    'submitted_at',
    'scored_at',
    'test_date',
  ],
  Assignments: [
    'id',
    'title',
    'task_type',
    'topic_id',
    'prompt',
    'image_file_id',
    'class_ids',
    'student_ids',
    'opens_at',
    'closes_at',
    'time_limit_minutes',
    'email_students',
    'created_at',
  ],
  Drafts: ['id', 'essay_id', 'kind', 'raw_text', 'parsed_json', 'created_at'],
  FeedbackSources: ['id', 'name', 'active'],
  SourceFeedback: [
    'id',
    'essay_id',
    'source_id',
    'criterion_1',
    'criterion_2',
    'criterion_3',
    'criterion_4',
    'overall',
    'feedback_text',
    'created_at',
  ],
  Scores: [
    'essay_id',
    'criterion_1',
    'criterion_2',
    'criterion_3',
    'criterion_4',
    'overall',
    'feedback_json',
    'general_comment',
    'updated_at',
  ],
  RewriteRequests: ['id', 'essay_id', 'due_at', 'note', 'status', 'rewrite_essay_id', 'created_at'],
  ErrorCategories: ['id', 'criterion', 'label', 'active'],
  ErrorLog: [
    'id',
    'essay_id',
    'student_id',
    'category_id',
    'excerpt',
    'start_offset',
    'end_offset',
    'correction',
    'note',
    'created_at',
  ],
  CalibrationSamples: ['id', 'essay_id', 'created_at'],
  EmailEvents: [
    'id',
    'essay_id',
    'user_id',
    'type',
    'idempotency_key',
    'status',
    'error',
    'created_at',
  ],
} as const;

export type TableName = keyof typeof SCHEMA;
export type Columns<T extends TableName> = (typeof SCHEMA)[T][number];
/** Every cell is stored and read back as text. */
export type Row<T extends TableName> = { [K in Columns<T>]: string };

export const TABLE_NAMES = Object.keys(SCHEMA) as TableName[];
